const GET_DATA_SAGA = 'GET_DATA_SAGA';
const GET_MODAL_SAGA = 'GET_MODAL_SAGA';
const SET_SERVICES = 'SET_SERVICES';
const SET_MODAL_CONTENT = 'SET_MODAL_CONTENT';
const INITIALIZE_MODAL = 'INITIALIZE_MODAL';

export {  //eslint-disable-line
  GET_DATA_SAGA,
  GET_MODAL_SAGA,
  SET_SERVICES,
  SET_MODAL_CONTENT,
  INITIALIZE_MODAL,
};
